name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push, workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest #ubuntu-latest
    steps:
      #- run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: test google 
        shell: pwsh
        run: Test-NetConnection www.google.com -Port 443
      - name: test
        shell: pwsh
        run: Test-NetConnection -ComputerName 168.153.42.65 -Port 443
     # - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      #- name: Check out repository code
      #  uses: actions/checkout@v3
      #- run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
     # - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
     # - name: List files in the repository
       # run: |
        #  ls ${{ github.workspace }}
      #- run: echo "ğŸ This job's status is ${{ job.status }}."
